/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report readiness and the server's current time.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Create the User, store the browser-detected `time_zone`, and log them in.
     */
    post: operations["register_api_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Log the User in, responding with a generic message on any failure.
     */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Revoke only the session carried by the caller's cookie.
     */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Return the current User's public fields only.
     */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Password
     * @description Change the password after confirming the current one, keeping only this session.
     */
    post: operations["change_password_api_auth_change_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/delete-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Delete Account
     * @description Confirm the password, then permanently delete the User and all of their data.
     */
    post: operations["delete_account_api_auth_delete_account_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Active Tasks
     * @description Return the User's Active Tasks (newest first), filtered by `filter_tasks`.
     */
    get: operations["list_active_tasks_api_tasks_active_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/archived": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Archived Tasks
     * @description Return the User's Archived Tasks (most recently archived first), filtered.
     *
     *     Never "in progress" (the Timer guard only applies to Active Tasks, and an
     *     Archived Task can't be started on in the first place), so no Timer lookup.
     */
    get: operations["list_archived_tasks_api_tasks_archived_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Task Counts
     * @description Return the Active/Archived tab counts.
     */
    get: operations["task_counts_api_tasks_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Task
     * @description Create a new Active Task, assigning Tags by name (creating/reusing per T4).
     */
    post: operations["create_task_api_tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/text": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit Text
     * @description Edit a Task's text, applying the same validation `create` uses.
     */
    patch: operations["edit_text_api_tasks__task_id__text_patch"];
    trace?: never;
  };
  "/api/tasks/{task_id}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit Tags
     * @description Replace a Task's Tag assignments with the given set of names.
     */
    patch: operations["edit_tags_api_tasks__task_id__tags_patch"];
    trace?: never;
  };
  "/api/tasks/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reorder Tasks
     * @description Rewrite the User's Active Tasks' positions to match the given full order.
     */
    post: operations["reorder_tasks_api_tasks_reorder_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive Task Route
     * @description Archive an Active Task, freezing its position.
     *
     *     Rejected while the User's Timer is running/paused/pending-log/on-break on
     *     this Task (user story #31): see `ensure_task_not_in_progress`.
     */
    post: operations["archive_task_route_api_tasks__task_id__archive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/unarchive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Unarchive Task Route
     * @description Unarchive a Task, sending it to the end of the Active list.
     *
     *     An Archived Task is never the one the Timer references (starting a
     *     Pomodoro requires an Active Task), so no Timer lookup is needed here.
     */
    post: operations["unarchive_task_route_api_tasks__task_id__unarchive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Task
     * @description Permanently delete a Task, only if it has zero Pomodoros and isn't in progress.
     */
    delete: operations["delete_task_api_tasks__task_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tags
     * @description Return the User's full Tag catalog, including orphaned Tags.
     */
    get: operations["list_tags_api_tags_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tags/{tag_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Tag Route
     * @description Delete a Tag; it's removed from every Task that had it, no confirmation required.
     */
    delete: operations["delete_tag_route_api_tags__tag_id__delete"];
    options?: never;
    head?: never;
    /**
     * Rename Tag Route
     * @description Rename a Tag; every Task carrying it reflects the new name without being touched.
     */
    patch: operations["rename_tag_route_api_tags__tag_id__patch"];
    trace?: never;
  };
  "/api/timer": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Timer
     * @description Return the settled Timer, the in-progress Task, remaining time and the server's `now`.
     */
    get: operations["get_timer_api_timer_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Day Summary
     * @description Return today's completed-Pomodoro count and how many more until the next long Break.
     */
    get: operations["get_day_summary_api_timer_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Timer
     * @description Start a Pomodoro on one of the caller's own Active Tasks.
     */
    post: operations["start_timer_api_timer_start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause Timer
     * @description PomodoroRunning/BreakRunning -> paused.
     */
    post: operations["pause_timer_api_timer_pause_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resume Timer
     * @description PomodoroPaused/BreakPaused -> running.
     */
    post: operations["resume_timer_api_timer_resume_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stop Timer
     * @description PomodoroRunning/PomodoroPaused + stop -> AskingToLog.
     */
    post: operations["stop_timer_api_timer_stop_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log Timer
     * @description AskingToLog + log -> Idle, persisting the interrupted Pomodoro's real time.
     *
     *     Persists through a compare-and-swap write so that two concurrent `/log`
     *     calls for the same stopped Pomodoro (two tabs, a retry, a double submit)
     *     can't both insert it: only the one that wins the CAS persists; the other
     *     re-settles against the now-Idle Timer and gets a 409, the same response
     *     an actually-stale tab already gets today.
     */
    post: operations["log_timer_api_timer_log_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/discard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Discard Timer
     * @description AskingToLog + discard -> Idle, persisting nothing.
     */
    post: operations["discard_timer_api_timer_discard_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/start-break": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Break Timer
     * @description ReadyForNext + start-break -> BreakRunning, short or long by cadence.
     */
    post: operations["start_break_timer_api_timer_start_break_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/skip-break": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Skip Break Timer
     * @description ReadyForNext/BreakRunning/BreakPaused + skip-break -> Idle, no Alarm.
     */
    post: operations["skip_break_timer_api_timer_skip_break_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/timer/next-pomodoro": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Next Pomodoro Timer
     * @description ReadyForNext + next-pomodoro -> PomodoroRunning on the same Task.
     */
    post: operations["next_pomodoro_timer_api_timer_next_pomodoro_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Settings Route
     * @description Return the current User's alarm/notifications/time_zone preferences.
     */
    get: operations["get_settings_route_api_settings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Settings Route
     * @description Update any subset of the User's preferences and persist the result.
     */
    patch: operations["update_settings_route_api_settings_patch"];
    trace?: never;
  };
  "/api/history/month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Month Heatmap
     * @description Return the User's per-day completed-Pomodoro count for the requested local month.
     */
    get: operations["get_month_heatmap_api_history_month_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/history/day": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Day Detail
     * @description Return, per Task worked on `date`, its completed count and dedicated time.
     *
     *     Includes Archived Tasks worked that day (story 81) and accepts the same
     *     name/tags filter query params as `/api/tasks` (story 82, 45).
     */
    get: operations["get_day_detail_api_history_day_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ChangePasswordRequest
     * @description Request body for `POST /api/auth/change-password`.
     */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /**
     * CreateTaskRequest
     * @description Request body for `POST /api/tasks`.
     */
    CreateTaskRequest: {
      /** Text */
      text: string;
      /**
       * Tags
       * @default []
       */
      tags: string[];
    };
    /**
     * DaySummaryPublic
     * @description Today's completed-Pomodoro count and the distance to the next long Break.
     */
    DaySummaryPublic: {
      /** Completed Today */
      completed_today: number;
      /** Until Long Break */
      until_long_break: number;
    };
    /**
     * DayTaskSummaryPublic
     * @description One Task's contribution to a single day: completed count and dedicated time.
     */
    DayTaskSummaryPublic: {
      /** Task Id */
      task_id: number;
      /** Text */
      text: string;
      /** Tags */
      tags: string[];
      /** Completed Count */
      completed_count: number;
      /** Dedicated Seconds */
      dedicated_seconds: number;
    };
    /**
     * DeleteAccountRequest
     * @description Request body for `POST /api/auth/delete-account`.
     */
    DeleteAccountRequest: {
      /** Password */
      password: string;
    };
    /**
     * EditTaskTagsRequest
     * @description Request body for `PATCH /api/tasks/{task_id}/tags`: the full desired Tag set.
     */
    EditTaskTagsRequest: {
      /** Tags */
      tags: string[];
    };
    /**
     * EditTaskTextRequest
     * @description Request body for `PATCH /api/tasks/{task_id}/text`.
     */
    EditTaskTextRequest: {
      /** Text */
      text: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Public shape of the health route's response.
     */
    HealthResponse: {
      /** Status */
      status: string;
      /**
       * Time
       * Format: date-time
       */
      time: string;
    };
    /**
     * InProgressTaskPublic
     * @description The minimal Task shape surfaced alongside the Timer.
     */
    InProgressTaskPublic: {
      /** Id */
      id: number;
      /** Text */
      text: string;
    };
    /**
     * LoginRequest
     * @description Request body for `POST /api/auth/login`.
     */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * MonthDayPublic
     * @description One local day's completed-Pomodoro count, for the heatmap.
     */
    MonthDayPublic: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Completed Count */
      completed_count: number;
    };
    /**
     * RegisterRequest
     * @description Request body for `POST /api/auth/register`.
     */
    RegisterRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /** Time Zone */
      time_zone: string;
    };
    /**
     * RenameTagRequest
     * @description Request body for `PATCH /api/tags/{tag_id}`.
     */
    RenameTagRequest: {
      /** Name */
      name: string;
    };
    /**
     * ReorderTasksRequest
     * @description Request body for `POST /api/tasks/reorder`: the full desired Active order.
     */
    ReorderTasksRequest: {
      /** Task Ids */
      task_ids: number[];
    };
    /**
     * SettingsPublic
     * @description The User's preference fields exposed over HTTP.
     */
    SettingsPublic: {
      /** Alarm Enabled */
      alarm_enabled: boolean;
      /** Notifications Enabled */
      notifications_enabled: boolean;
      /** Time Zone */
      time_zone: string;
    };
    /**
     * StartTimerRequest
     * @description Request body for `POST /api/timer/start`.
     */
    StartTimerRequest: {
      /** Task Id */
      task_id: number;
    };
    /**
     * TagPublic
     * @description A Tag as exposed over HTTP.
     */
    TagPublic: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /**
     * TaskCountsPublic
     * @description Tab counts for the Active/Archived tabs.
     */
    TaskCountsPublic: {
      /** Active */
      active: number;
      /** Archived */
      archived: number;
    };
    /**
     * TaskPublic
     * @description A Task as exposed over HTTP: Tags by name, plus the computed `deletable` flag.
     */
    TaskPublic: {
      /** Id */
      id: number;
      /** Text */
      text: string;
      /** Position */
      position: number;
      /** Tags */
      tags: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Archived At */
      archived_at: string | null;
      /** Deletable */
      deletable: boolean;
    };
    /**
     * TimerPublic
     * @description The settled Timer as exposed over HTTP, plus client clock-offset correction data.
     */
    TimerPublic: {
      /** Phase */
      phase: string;
      task: components["schemas"]["InProgressTaskPublic"] | null;
      /** Break Kind */
      break_kind: string | null;
      /** Remaining Seconds */
      remaining_seconds: number | null;
      /**
       * Server Now
       * Format: date-time
       */
      server_now: string;
    };
    /**
     * UpdateSettingsRequest
     * @description Request body for `PATCH /api/settings`; every field is optional.
     */
    UpdateSettingsRequest: {
      /** Alarm Enabled */
      alarm_enabled?: boolean | null;
      /** Notifications Enabled */
      notifications_enabled?: boolean | null;
      /** Time Zone */
      time_zone?: string | null;
    };
    /**
     * UserPublic
     * @description The User's public fields: never a password hash or any `*_key` column.
     */
    UserPublic: {
      /** Id */
      id: number;
      /** Email */
      email: string;
      /** Time Zone */
      time_zone: string;
      /** Alarm Enabled */
      alarm_enabled: boolean;
      /** Notifications Enabled */
      notifications_enabled: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  register_api_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
    };
  };
  change_password_api_auth_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_account_api_auth_delete_account_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteAccountRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_active_tasks_api_tasks_active_get: {
    parameters: {
      query?: {
        tags?: string[];
        text?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_archived_tasks_api_tasks_archived_get: {
    parameters: {
      query?: {
        tags?: string[];
        text?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  task_counts_api_tasks_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskCountsPublic"];
        };
      };
    };
  };
  create_task_api_tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_text_api_tasks__task_id__text_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditTaskTextRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_tags_api_tasks__task_id__tags_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditTaskTagsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reorder_tasks_api_tasks_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderTasksRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_task_route_api_tasks__task_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unarchive_task_route_api_tasks__task_id__unarchive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_task_api_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tags_api_tags_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagPublic"][];
        };
      };
    };
  };
  delete_tag_route_api_tags__tag_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tag_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rename_tag_route_api_tags__tag_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tag_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameTagRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_timer_api_timer_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  get_day_summary_api_timer_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DaySummaryPublic"];
        };
      };
    };
  };
  start_timer_api_timer_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartTimerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pause_timer_api_timer_pause_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  resume_timer_api_timer_resume_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  stop_timer_api_timer_stop_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  log_timer_api_timer_log_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  discard_timer_api_timer_discard_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  start_break_timer_api_timer_start_break_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  skip_break_timer_api_timer_skip_break_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  next_pomodoro_timer_api_timer_next_pomodoro_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerPublic"];
        };
      };
    };
  };
  get_settings_route_api_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsPublic"];
        };
      };
    };
  };
  update_settings_route_api_settings_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSettingsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_month_heatmap_api_history_month_get: {
    parameters: {
      query: {
        year: number;
        month: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MonthDayPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_day_detail_api_history_day_get: {
    parameters: {
      query: {
        date: string;
        tags?: string[];
        text?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DayTaskSummaryPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
