"""Initial schema.

Revision ID: 0001
Revises:
Create Date: 2026-10-09 12:54:45.370086
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
import sqlmodel
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_key", sa.String(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time_zone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alarm_enabled", sa.Boolean(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_key"),
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_session", schema=None) as batch_op:
        batch_op.create_index("ix_auth_session_user_id", ["user_id"], unique=False)

    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name_key", name="uq_tag_user_id_name_key"),
    )
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.create_index("ix_tag_user_id", ["user_id"], unique=False)

    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            "ix_task_active_text_key",
            ["user_id", "text_key"],
            unique=True,
            sqlite_where=sa.text("archived_at IS NULL"),
            postgresql_where=sa.text("archived_at IS NULL"),
        )
        batch_op.create_index("ix_task_user_id", ["user_id"], unique=False)

    op.create_table(
        "pomodoro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "status IN ('completed', 'interrupted_logged')", name="ck_pomodoro_status_valid"
        ),
        sa.CheckConstraint("duration_seconds > 0", name="ck_pomodoro_duration_positive"),
        sa.CheckConstraint("ended_at >= started_at", name="ck_pomodoro_ended_after_started"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pomodoro", schema=None) as batch_op:
        batch_op.create_index("ix_pomodoro_task_id", ["task_id"], unique=False)
        batch_op.create_index("ix_pomodoro_user_id_ended_at", ["user_id", "ended_at"], unique=False)

    op.create_table(
        "task_tags",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "tag_id"),
    )
    with op.batch_alter_table("task_tags", schema=None) as batch_op:
        batch_op.create_index("ix_task_tags_tag_id", ["tag_id"], unique=False)

    op.create_table(
        "timer",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("break_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phase_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accumulated_active_seconds", sa.Integer(), nullable=False),
        sa.Column("running_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phase_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timer")
    with op.batch_alter_table("task_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_task_tags_tag_id")

    op.drop_table("task_tags")
    with op.batch_alter_table("pomodoro", schema=None) as batch_op:
        batch_op.drop_index("ix_pomodoro_user_id_ended_at")
        batch_op.drop_index("ix_pomodoro_task_id")

    op.drop_table("pomodoro")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index("ix_task_user_id")
        batch_op.drop_index(
            "ix_task_active_text_key",
            sqlite_where=sa.text("archived_at IS NULL"),
            postgresql_where=sa.text("archived_at IS NULL"),
        )

    op.drop_table("task")
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_user_id")

    op.drop_table("tag")
    with op.batch_alter_table("auth_session", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_session_user_id")

    op.drop_table("auth_session")
    op.drop_table("user")
    # ### end Alembic commands ###
