"""Initial schema.

Revision ID: 9c8f6e5130a9
Revises:
Create Date: 2026-10-04 19:23:28.895939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

from pomodoro.database.types import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "9c8f6e5130a9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("email_key", AutoString(), nullable=False),
        sa.Column("password_hash", AutoString(), nullable=False),
        sa.Column("time_zone", AutoString(), nullable=False),
        sa.Column("alarm_enabled", sa.Boolean(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email_key"), "user", ["email_key"], unique=True)
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", AutoString(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_session_token_hash"), "auth_session", ["token_hash"], unique=True)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("name_key", AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name_key", name="uq_tag_user_id_name_key"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", AutoString(), nullable=False),
        sa.Column("text_key", AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("archived_at", UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_user_id_text_key_active",
        "task",
        ["user_id", "text_key"],
        unique=True,
        sqlite_where=sa.text("archived_at IS NULL"),
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "pomodoro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("started_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("ended_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("status", AutoString(), nullable=False),
        sa.CheckConstraint(
            "status IN ('completed', 'interrupted_logged')", name="ck_pomodoro_status"
        ),
        sa.CheckConstraint("duration_seconds > 0", name="ck_pomodoro_duration_positive"),
        sa.CheckConstraint("ended_at >= started_at", name="ck_pomodoro_ended_after_started"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pomodoro_task_id", "pomodoro", ["task_id"], unique=False)
    op.create_index(
        "ix_pomodoro_user_id_ended_at", "pomodoro", ["user_id", "ended_at"], unique=False
    )
    op.create_table(
        "task_tags",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "tag_id"),
    )
    op.create_index("ix_task_tags_tag_id", "task_tags", ["tag_id"], unique=False)
    op.create_table(
        "timer",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phase", AutoString(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("break_kind", AutoString(), nullable=True),
        sa.Column("phase_started_at", UTCDateTime(timezone=True), nullable=True),
        sa.Column("accumulated_active_seconds", sa.Integer(), nullable=False),
        sa.Column("running_since", UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timer")
    op.drop_index("ix_task_tags_tag_id", table_name="task_tags")
    op.drop_table("task_tags")
    op.drop_index("ix_pomodoro_user_id_ended_at", table_name="pomodoro")
    op.drop_index("ix_pomodoro_task_id", table_name="pomodoro")
    op.drop_table("pomodoro")
    op.drop_index(
        "ix_task_user_id_text_key_active",
        table_name="task",
        sqlite_where=sa.text("archived_at IS NULL"),
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("task")
    op.drop_table("tag")
    op.drop_index(op.f("ix_auth_session_token_hash"), table_name="auth_session")
    op.drop_table("auth_session")
    op.drop_index(op.f("ix_user_email_key"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
